package com.scholarum.common.type;

public enum Role {

	ROLE_SCHOLARUM_ADMIN, ROLE_SCHOLARUM_SUPERVISOR, ROLE_SCHOLARUM_FINANCE, ROLE_SCHOLARUM_OPS, ROLE_SCHOLARUM_ADVISOR,
	ROLE_INSTITUTION_ADMIN, ROLE_INSTITUTION_SUPERVISOR, ROLE_INSTITUTION_FINANCE, ROLE_INSTITUTION_OPS,
	ROLE_SCHOOL_ADMIN, ROLE_SCHOOL_FINANCE, ROLE_SCHOOL_OPS, ROLE_SCHOOL_TEACHER, ROLE_SCHOOL_STAFF;

}
