package com.scholarum.common.type;

public enum Role {

	ROLE_SCHOLARUM, ROLE_SCHOLARUM_SUPERVISOR, ROLE_SCHOLARUM_FINANCE, ROLE_SCHOLARUM_OPS, ROLE_SCHOLARUM_ADVISOR, ROLE_SCHOOL, ROLE_SCHOOL_FINANCE, ROLE_SCHOOL_OPS;

}
