package com.scholarum.common.type;

public enum Role {

	ROLE_SCHOLARUM, ROLE_SCHOLARUM_SUPERVISOR, ROLE_SCHOLARUM_FINANCE, ROLE_SCHOLARUM_OPS, ROLE_SCHOLARUM_ADVISOR, ROLE_MERCHANT, ROLE_MERCHANT_FINANCE, ROLE_MERCHANT_OPS;

}
