package com.scholarum.common.type;

public enum RoleType {

	ROLE_SCHOLARUM_ADMIN("SUPER_ADMIN"), ROLE_SCHOLARUM_SUPERVISOR("SUPERVISOR"), ROLE_SCHOLARUM_FINANCE("FINANCE"), ROLE_SCHOLARUM_OPS("OPERATIONS"),
	ROLE_INSTITUTION_ADMIN("ADMIN"), ROLE_INSTITUTION_SUPERVISOR("ADVISOR"), ROLE_INSTITUTION_FINANCE("FINANCE"), ROLE_INSTITUTION_OPS("OPERATIONS"),
	ROLE_SCHOOL_ADMIN("ADMIN"), ROLE_SCHOOL_SUPERVISOR("SUPERVISOR"), ROLE_SCHOOL_FINANCE("FINANCE"), ROLE_SCHOOL_OPS("OPERATIONS"), ROLE_SCHOOL_TEACHER("TEACHER"), ROLE_SCHOOL_STAFF("STAFF");

	private String alias;
	
	private RoleType(String alias) {
		this.alias = alias;
	}

	public String getAlias() {
		return alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

}
